### ISSUE TITLE
Answer width Problem

### ISSUE THREAD

**Issue by halilyuce** [Abedalkareem/AMChoice#1]
Hi bro, thanks for this but there is important problem for use it.
If your answers are short its good but else your answers are long its not showing more than one line.
If you fix, it will be more usefull, thanks :)

<img width="1062" alt="ekran resmi 2019-01-03 15 06 16" src="https://user-images.githubusercontent.com/29376592/50636966-25b34880-0f69-11e9-80df-e54b93212fa9.png">

**Comment by Abedalkareem** [comment]
Hi,

Thank you for reporting!
The issue fixed.
